name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.4
        with:
          fail-threshold: 1

